name: Update Produce Prices

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggers

permissions:
  contents: write

jobs:
  update-prices:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install uv
        run: |
          python -m pip install uv

      - name: Create venv
        run: uv venv
          
      - name: Install dependencies
        run: uv pip install -e .
          
      - name: Run price scraper
        run: uv run python src/coop/pull_prices.py
        
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
      - name: Commit and push changes
        run: |
          git add index.html
          git commit -m "Update produce prices for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
